### ISSUE TITLE
Add support for inverter size query param

### ISSUE THREAD

**Issue by binsentsu** [home-assistant-libs/forecast_solar#16]
Hi,

The forecast solar added a general query parameter (cfr damping) for defining the inverter size.
Could be an interesting option to use in cases where the inverter is underdimensioned in relation to the total kwp of the solarpanels. This happens to be the case in a lot of Belgian installations due to taxation based on inverter size. 
Must admit that to me it's not clear from the forecast documentation if the outcome would be different from setting the kwp parameter to the max inverter size.

https://doc.forecast.solar/doku.php?id=api

What do you think?

**Comment by klaasnicolaas** [comment]
What is not really clear to me is how much this is different from the modules_power.

**Comment by jesserockz** [comment]
@klaasnicolaas If you have more solar potential for example 7kW of panels, and only a 5kW inverter, then you will get a different result as the calculation can take into account more panels so you get more energy earlier and later in the day, but the peak will be limited to the inverter size.
