### ISSUE TITLE
HTTP status code

### ISSUE THREAD

**Issue by K-Ko** [home-assistant-libs/forecast_solar#22]
https://github.com/home-assistant-libs/forecast_solar/blob/9f76595f6978a91c938e780b988c39fb763fd8a0/forecast_solar/__init__.py#L116

Could you please also check for `401 Unauthorized`?

I will add this in future to differentiate from `403 Forbidden`.

- 400 - Wrong API key format, matches not `/[a-z0-9]{16}/`
- 401 - Known but expired API key
- 403 - Valid API key format, but unknown

**Comment by frenck** [comment]
Feel free to contribute 👍

**Comment by K-Ko** [comment]
👍😊


Am 21.03.2022 18:49:02 schrieb Franck Nijhof ***@***.***>:
Feel free to contribute 👍
