### ISSUE TITLE
[Feature Request] : Add all estimated hours as attributes to sensors

### ISSUE THREAD

**Issue by LasseHedeby** [home-assistant-libs/forecast_solar#26]
Hi

A nice feature could be to add all estimated hours as attributes to a sensor. Now I can see estimated next hours, but the other sensors (+6h, +12h, +24h) is accumulated instead of each hour.
The data is available from the API so it should be fairly easy to add as attributes:

"result": {
        "2022-08-19 06:00:00": 0,
        "2022-08-19 07:00:00": 14,
        "2022-08-19 08:00:00": 59,
        "2022-08-19 09:00:00": 143,
        "2022-08-19 10:00:00": 224,
        "2022-08-19 11:00:00": 294,
        "2022-08-19 12:00:00": 375,
        "2022-08-19 13:00:00": 461,
        "2022-08-19 14:00:00": 577,
        "2022-08-19 15:00:00": 792,
        "2022-08-19 16:00:00": 1128,
        "2022-08-19 17:00:00": 1471,
        "2022-08-19 18:00:00": 1679,
        "2022-08-19 19:00:00": 1757,
        "2022-08-19 20:00:00": 1778,
        "2022-08-19 20:30:00": 1779,
        "2022-08-20 06:02:00": 0,
        "2022-08-20 07:00:00": 78,
        "2022-08-20 08:00:00": 335,
        "2022-08-20 09:00:00": 704,
        "2022-08-20 10:00:00": 1018,
        "2022-08-20 11:00:00": 1205,
        "2022-08-20 12:00:00": 1401,
        "2022-08-20 13:00:00": 1725,
        "2022-08-20 14:00:00": 2090,
        "2022-08-20 15:00:00": 2477,
        "2022-08-20 16:00:00": 2933,
        "2022-08-20 17:00:00": 3341,
        "2022-08-20 18:00:00": 3675,
        "2022-08-20 19:00:00": 3924,
        "2022-08-20 20:00:00": 4044,
        "2022-08-20 20:28:00": 4062
    }

**Comment by klaasnicolaas** [comment]
I wonder if you are in the right place for this feature request. By sensors do you mean the entities in Home Assistant?

**Comment by LasseHedeby** [comment]
> 
Yes, I do mean entities in Home Assistant but for the Forecast.Solar integration. So I would expect this to be the right place for the entities under this integration??

**Comment by klaasnicolaas** [comment]
This repository is not the right place for that. A feature request can be created on the community forum and upvoted if more people want this feature.

https://community.home-assistant.io/c/feature-requests

**Comment by georgbachmann** [comment]
@LasseHedeby did you ever write a feature-request? Could not find something on the community page? Cause I'd also love to see hourly estimated data to visualize with something like this here: https://github.com/RomRider/apexcharts-card
