### ISSUE TITLE
Usage without async

### ISSUE THREAD

**Issue by henfri** [home-assistant-libs/forecast_solar#30]
Hello,

thanks for this library!
I am using a threaded application to which I would like to use forecast_solar.
In the past, I had issues using async in it.
Can you provide an examle not using async?

Best regards,
Hendrik

**Comment by klaasnicolaas** [comment]
the package is written completely async, so there is no sync example

**Comment by frenck** [comment]
As per above, I'm closing this issue, as no example can be given.
