### ISSUE TITLE
energy_current_hour will show wrong value with paid subscription

### ISSUE THREAD

**Issue by ianmcorvidae** [home-assistant-libs/forecast_solar#31]
Since `energy_current_hour` uses `_timed_value`, it will directly return one Wh/kWh value from what the forecast.solar API returns. For the public forecast.solar API, this works out to an hour because that is the data resolution, but for any paid subscription the data resolution is lower (30 minutes for Personal, 15 minutes for Personal Plus and higher). So for example when I switched from public to using an API key, my current hour estimate dropped from about 6 kWh to about 1.5, because it actually became a 15-minute estimate. For these tiers, it should do a sum of all the values for the hour instead of using a value directly from the array.

**Comment by koleo9am** [comment]
I have prepared a correction

https://github.com/koleo9am/forecast_solar/tree/issue_31
