### ISSUE TITLE
no entities after reinstall

### ISSUE THREAD

**Issue by bmwmotor** [home-assistant-libs/forecast_solar#35]
I am getting the 429 error on the public without API. After deleting and reinstall forecast.solar in HA it is still the same issue.
But now I am missing also al the entities from forecast_solar. How can I get it back working again ?
With regards

**Comment by frenck** [comment]
Sounds like you have an issue with the Home Assistant integration. This is de issue tracker of the Python library, not Home Assistant.

You can find the issue tracker of the Home Assistant project here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
